---
apiVersion: v1
kind: Service
metadata:
  name: canary-demo-stable
  namespace: demo
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  selector:
    app: canary-demo
  ports:
    - port: 80
      targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: canary-demo-canary
  namespace: demo
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  selector:
    app: canary-demo
  ports:
    - port: 80
      targetPort: 8080
