---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: victoria-metrics
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://victoriametrics.github.io/helm-charts
    chart: victoria-metrics-single
    targetRevision: "0.33.0"
    helm:
      valuesObject:
        server:
          fullnameOverride: victoria-metrics-server
          retentionPeriod: "7d"
          resources:
            requests:
              cpu: 100m
              memory: 512Mi
            limits:
              memory: 1Gi
          persistentVolume:
            size: 10Gi
          scrape:
            enabled: true
  destination:
    server: https://kubernetes.default.svc
    namespace: victoria-metrics
  syncPolicy:
    automated:
      selfHeal: false
      prune: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
