---
- name: Add ArgoCD Helm repository
  kubernetes.core.helm_repository:
    name: argo
    repo_url: https://argoproj.github.io/argo-helm

- name: Install ArgoCD
  kubernetes.core.helm:
    release_name: argocd
    chart_ref: argo/argo-cd
    release_namespace: argocd
    chart_version: "{{ argocd_chart_version }}"
    create_namespace: true
    kubeconfig: "{{ kubeconfig }}"
    wait: true
    wait_timeout: 5m0s
    release_values:
      configs:
        params:
          server.insecure: true  # TLS terminates at Cloudflare edge
      server:
        extensions:
          enabled: true
          extensionList:
            - name: rollout-extension
              env:
                - name: EXTENSION_URL
                  value: https://github.com/argoproj-labs/rollout-extension/releases/download/v0.3.7/extension.tar
