---
- name: Ensure cloudflared namespace exists
  kubernetes.core.k8s:
    kubeconfig: "{{ kubeconfig }}"
    state: present
    resource_definition:
      apiVersion: v1
      kind: Namespace
      metadata:
        name: cloudflared

- name: Create Cloudflared tunnel token secret
  kubernetes.core.k8s:
    kubeconfig: "{{ kubeconfig }}"
    state: present
    resource_definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: cloudflared-tunnel-token
        namespace: cloudflared
      stringData:
        token: "{{ vault_cloudflared_tunnel_token }}"
