{{- if .Values.keda.enabled }}
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: {{ include "rollouts-demo.name" . }}
  labels:
    {{- include "rollouts-demo.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: argoproj.io/v1alpha1
    kind: Rollout
    name: {{ include "rollouts-demo.name" . }}
  minReplicaCount: {{ .Values.keda.minReplicas }}
  maxReplicaCount: {{ .Values.keda.maxReplicas }}
  {{- with .Values.keda.pollingInterval }}
  pollingInterval: {{ . }}
  {{- end }}
  {{- with .Values.keda.cooldownPeriod }}
  cooldownPeriod: {{ . }}
  {{- end }}
  triggers:
    {{- toYaml .Values.keda.triggers | nindent 4 }}
  {{- with .Values.keda.advanced }}
  advanced:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}