apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pathfinder
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: default
  source:
    repoURL: https://github.com/yourdevops/pathfinder.git
    targetRevision: main
    path: chart
    helm:
      valuesObject:
        image:
          repository: ghcr.io/yourdevops/pathfinder
          tag: sha-701765e
        config:
          allowedHosts: "pathfinder.yourdevops.me"
          csrfTrustedOrigins: "https://pathfinder.yourdevops.me"
        ingress:
          enabled: true
          className: traefik
          hosts:
            - host: pathfinder.yourdevops.me
              paths:
                - path: /
                  pathType: Prefix
  destination:
    server: https://kubernetes.default.svc
    namespace: pathfinder
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
