---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keda
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://kedacore.github.io/charts
    chart: keda
    targetRevision: "2.19.0"
    helm:
      valuesObject:
        operator:
          replicaCount: 1
        metricsServer:
          replicaCount: 1
        webhooks:
          replicaCount: 1
        crds:
          install: true
        resources:
          operator:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              memory: 256Mi
          metricsServer:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              memory: 256Mi
          webhooks:
            requests:
              cpu: 25m
              memory: 64Mi
            limits:
              memory: 128Mi
  destination:
    server: https://kubernetes.default.svc
    namespace: keda
  syncPolicy:
    automated:
      selfHeal: false
      prune: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
